site_name: Python DispmanX
site_url: https://dtcooper.github.io/python-dispmanx/
repo_url: https://github.com/dtcooper/python-dispmanx
repo_name: dtcooper/python-dispmanx
edit_uri: ""
copyright: Copyright &copy; 2022 David Cooper
strict: true
nav:
  - index.md
  - recipes.md
  - api.md
  - more-info.md
  - license.md
extra_css:
  - assets/extra.css
plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://docs.scipy.org/doc/numpy/objects.inv
          options:
            docstring_section_style: table
            docstring_style: google
            merge_init_into_class: true
            show_root_full_path: false
            show_root_heading: true
            show_source: false
            show_signature_annotations: true
            line_length: 100
watch:
  - ./examples
  - ./dispmanx
markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.snippets:
      base_path: [ "./examples", "LICENSE" ]
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: "\u2190"
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/dtcooper
      name: '@dtcooper on Twitter'
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/dtcooper
      name: '@dtcooper on Instagram'
    - icon: fontawesome/solid/radio
      link: https://www.iheartradio.ca/newstalk-1010/host/Person/David%20Cooper
      name: My bio on iHeartRadio
    - icon: fontawesome/solid/globe
      link: https://jew.pizza/
      name: My personal website
theme:
  name: material
  favicon: assets/favicon.svg
  features:
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - search.highlight
    - search.suggest
    - toc.integrate
  icon:
    logo: fontawesome/brands/raspberry-pi
    repo: fontawesome/brands/github
  font:
    text: Space Grotesk
    code: Space Mono  # ligatures disabled in extra.css
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: pink
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: pink
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
