site_name: My Docs

site_url: https://dtcooper.github.io/python-dispmanx/
repo_url: https://github.com/dtcooper/python-dispmanx
repo_name: python-dispmanx
edit_uri: ""
copyright: Copyright &copy; 2022 David Cooper

nav:
  - Welcome: index.md

extra_css:
  - assets/extra.css
plugins:
  - search
watch:
  - "./examples"
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: [ "./examples" ]
      check_paths: true
  - pymdownx.superfences
  - toc:
      permalink: True
extra:
  version:
    provider: mike
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/dtcooper
      name: '@dtcooper on Twitter'
theme:
  name: material
  favicon: assets/favicon.svg
  features:
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - search.highlight
    - search.suggest
    - toc.integrate
  icon:
    logo: fontawesome/brands/raspberry-pi
    repo: fontawesome/brands/github
  # font:
  #   text: Space Grotesk
  #   code: Space Mono  # ligatures disabled in extra.css
  palette:
    - scheme: slate
      primary: pink
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: dark blue
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
