name: Publish docs

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Publish
    env:
      POETRY_VERSION: 1.1.14
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          # Get a full clone so there's a local copy of gh-pages to commit to
          fetch-depth: 0
      -
        name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      -
        name: Setup requirements
        run: |
          curl -sSL https://install.python-poetry.org | python -
          poetry install
          git config user.name 'Docs Deploy'
          git config user.email 'docs-deploy@users.noreply.github.com'
      -
        name: Deploy dev docs
        run: |
          poetry run mike deploy --push dev
      -
        name: Deploy latest docs
        if: startsWith(github.event.ref, 'refs/tags/v')
        run: |
          poerty run mike deploy --push --update-aliases ${{ github.ref_name }} latest
