name: Publish to PyPI

on:
  push:
    tags:
      # Publish when tags start with v
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Publish
    env:
      POETRY_VERSION: 1.1.14
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      -
        name: Publish to PyPI
        run: |
          curl -sSL https://install.python-poetry.org | python -
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry install --no-dev
          poetry build
          poetry publish
